import { readFileSync, existsSync } from "fs";
import { join } from "path";

export interface CalendarEvent {
  id: string;
  title: string;
  description: string;
  date: string;
  startTime: string;
  endTime: string;
  venue: string;
  address: string;
  price: string;
  level: string;
  type: string;
  organizer: string;
  url?: string;
  instagram?: string;
  website?: string;
  isRecurring?: boolean;
}

export async function fetchGoogleCalendarEvents(calendarId?: string) {
  try {
    // Read from local JSON file (generated by fetch-calendar.js)
    const jsonPath = join(process.cwd(), "src/data/events.json");
    if (existsSync(jsonPath)) {
      console.log("[Calendar] Reading from events.json");
      const jsonData = readFileSync(jsonPath, "utf-8");
      const events: CalendarEvent[] = JSON.parse(jsonData);
      return events;
    } else {
      console.warn("[Calendar] No events.json found. Run 'node scripts/fetch-calendar.js' to populate it.");
      return [];
    }
  } catch (error) {
    console.error("Error loading calendar events:", error);
    return [];
  }
}


